version: "3"
services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256M" 

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tweetstream:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: producer
    depends_on:
      - kafka
    environment:
      KAFKA_SERVICE: kafka:9092



  consumer:
    image: consumer
    depends_on:
      - kafka
      - mongo
    environment:
      KAFKA_SERVICE: kafka:9092



  notebook:
    image: johnkurian/ds-notebook:v5
    depends_on:
      - mongo
    ports:
      - "443:8888"
    deploy:
      resources:
        reservations:
          memory: 3000M


#networks:
#  app-tier:
